version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install
      - run:
          name: Create test config
          command: "echo -e '{\t\"api_keys\": [\n\t\t\"1234567\"\n\t],\n\t\"server_port\": 3000\n}' > config.json"
      - run:
          name: Running tests
          command: npm run cover
      - run:
          name: Install codeclimate reporter
          command: sudo npm install -g codeclimate-test-reporter
      - run:
          name: Upload test result to codeclimate
          command: codeclimate-test-reporter < coverage/lcov.info
      - run:
          name: Upload test result to codecov
          command: bash <(curl -s https://codecov.io/bash)